version: '3.9'

services:
  app:
    container_name: nequo_app
    restart: always
    depends_on:
      - database
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - PG_HOST=database
    volumes:
      - ./:/home/node/app
    command: node ace serve --watch --no-assets

  encore:
    image: nequo-api_app
    container_name: nequo_app_encore
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/home/node/app
    command: npx encore dev-server --host 0.0.0.0 --port 8080

  database:
    image: postgres:13
    container_name: nequo_database
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nequo
      - POSTGRES_PASSWORD=nequo
      - POSTGRES_DB=nequo

  test_database:
    image: postgres:13
    container_name: nequo_test_database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=nequo_test
      - POSTGRES_PASSWORD=nequo_test
      - POSTGRES_DB=nequo_test

volumes:
  database_volume: